[package]
name = "external-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-worker.workspace = true
chirp-client.workspace = true
reqwest = { version = "0.12" }
rivet-health-checks.workspace = true
rivet-metrics.workspace = true
rivet-runtime.workspace = true
chrono = "0.4"
rivet-config.workspace = true

[dev-dependencies]
chirp-worker.workspace = true
