[package]
name = "monolith-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
rivet-config.workspace = true
rivet-connection.workspace = true
rivet-health-checks.workspace = true
rivet-metrics.workspace = true
rivet-operation.workspace = true
rivet-runtime.workspace = true
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }

cdn-worker.workspace = true
cf-custom-hostname-worker.workspace = true
cloud-worker.workspace = true
external-worker.workspace = true
job-log-worker.workspace = true
job-run.workspace = true
mm-worker.workspace = true
team-invite-worker.workspace = true
team-worker.workspace = true
upload-worker.workspace = true
user-worker.workspace = true
