[package]
name = "chat-thread-unread-count"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
chrono = "0.4"
prost = "0.10"
serde_json = "1.0"

chat-last-read-ts-get = { path = "../../../chat/ops/last-read-ts-get" }

[dependencies.sqlx]
version = "0.7"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

chat-thread-get-or-create-for-topic = { path = "../get-or-create-for-topic" }
faker-user = { path = "../../../faker/ops/user" }
