[package]
name = "rivet-operation"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"
chirp-client.workspace = true
chirp-metrics.workspace = true
chirp-perf.workspace = true
formatted-error.workspace = true
futures-util = "0.3"
global-error.workspace = true
indoc = "1.0"
prost = "0.10"
prost-types = "0.10"
rivet-cache.workspace = true
rivet-config.workspace = true
rivet-connection.workspace = true
rivet-operation-macros.workspace = true
rivet-pools.workspace = true
rivet-util.workspace = true
serde_json = { version = "1.0", features = ["raw_value"] }
thiserror = "1.0"
tokio.workspace = true
tracing = "0.1"
types-proto.workspace = true
