[package]
name = "api-edge-monolith-edge"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
api-helper.workspace = true
async-trait = "0.1"
chirp-client.workspace = true
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }
rivet-config.workspace = true
rivet-env.workspace = true
rivet-operation.workspace = true
tokio.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"

api-edge-traefik-provider.workspace = true
