[package]
name = "analytics-worker"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
chirp-client = { path = "../../../../lib/chirp/client" }
clickhouse = { version = "0.11.2", features = ["wa-37420", "uuid"] }
lazy_static = "1.4.0"
prost = "0.10"
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
serde = { version = "1.0", features = ["derive"] }

reqwest = "0.11"

user-presence-get = { path = "../../user-presence/ops/get" }

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }

faker-user = { path = "../../faker/ops/user" }
faker-game = { path = "../../faker/ops/game" }
