[package]
name = "monolith-workflow-worker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-workflow.workspace = true
rivet-health-checks.workspace = true
rivet-metrics.workspace = true
rivet-runtime.workspace = true

cluster.workspace = true
ds.workspace = true
job-run.workspace = true
linode.workspace = true
pegboard.workspace = true
rivet-config.workspace = true
user.workspace = true
