[package]
name = "user-delete-pending"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
lazy_static = "1.4"
chirp-client.workspace = true
chirp-workflow.workspace = true
rivet-operation.workspace = true
futures-util = "0.3"
indoc = "1.0"
prost = "0.10"
rivet-connection.workspace = true
rivet-pools.workspace = true
rivet-runtime.workspace = true
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
tracing-logfmt = "0.3"
rivet-config.workspace = true
user.workspace = true

[dev-dependencies]
chirp-worker.workspace = true
chrono = "0.4"
