[service]
name = "api-job"
essential = true

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/job"
subdomain = "api"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "job.api"

