client:
  data_dir: /data/rivet-client
  runner:
    flavor: isolate
    # Enables running in non-privileged Docker containers
    use_mounts: false
  cluster:
    # This is safe to hardcode
    client_id: fc67e54e-5d6a-4726-ab23-77b0e54f068f
    # This is hardcoded to match the value in rivet-server/config.jsonc
    datacenter_id: f288913c-735d-4188-bf9b-2fcf6eac7b9c
    api_endpoint: http://rivet-server:8080
    pegboard_endpoint: ws://rivet-server:8082
  network:
    bind_ip: 127.0.0.1
    # Point to DNS name inside Docker container
    lan_hostname: 127.0.0.1
    # Point to localhost since this is a dev instance
    wan_hostname: 127.0.0.1
    # Corresponds to the port range configured in the `docker-compose.yml`
    wan_port_range_min: 7600
    wan_port_range_max: 7699
  cni:
    network_interface: eth0
  # Don't reserve any resources on dev instances
  reserved_resources:
    cpu: 0
    memory: 0
  logs:
    redirect_logs: false
  foundationdb:
    cluster_description: fdb
    cluster_id: fdb
    addresses:
      !static
      - "127.0.0.1:4500"
  vector:
    address: vector-server:6100
