[package]
name = "rivet-connection"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
chirp-perf.workspace = true
global-error.workspace = true
rivet-cache.workspace = true
rivet-pools.workspace = true
rivet-util.workspace = true
tracing = "0.1"
fdb-util.workspace = true

