[package]
name = "cloud-namespace-get"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
prost = "0.10"

cdn-namespace-get = { path = "../../../cdn/ops/namespace-get" }
identity-config-namespace-get = { path = "../../../identity-config/ops/namespace-get" }
kv-config-namespace-get = { path = "../../../kv-config/ops/namespace-get" }
mm-config-namespace-get = { path = "../../../mm-config/ops/namespace-get" }

[dependencies.sqlx]
version = "0.7"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

cloud-namespace-create = { path = "../namespace-create" }
faker-game = { path = "../../../faker/ops/game" }
game-namespace-create = { path = "../../../game/ops/namespace-create" }
game-version-create = { path = "../../../game/ops/version-create" }
