[package]
name = "rivet-cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "rivet"
path = "src/main.rs"

[features]
default = ["sentry"]
sentry = []

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
toolchain = { path = "../toolchain", package = "rivet-toolchain" }
tokio.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
anyhow = "1.0"
uuid = { version = "1.11.0", features = ["v4"] }
url = { version = "2.5.3", features = ["serde"] }
base64 = "0.22.1"
kv-str.workspace = true
inquire = "0.7.5"
webbrowser = "1.0.2"
sentry = { version = "0.34.0", features = ["anyhow"] }
sysinfo = "0.32.0"
ctrlc = "3.4.5"
async-posthog.workspace = true
deno-embed.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", default-features = false, features = ["user", "signal"] }

[build-dependencies]
anyhow = "1.0"

[build-dependencies.vergen]
version = "9.0.4"
features = [
  "build",
  "cargo",
  "rustc"
]

