[package]
name = "captcha-turnstile-verify"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-operation.workspace = true
chirp-client.workspace = true
prost = "0.10"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
chirp-worker.workspace = true
