[package]
name = "game-version-validate"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
prost = "0.10"
util-mm = { package = "rivet-util-mm", path = "../../../mm/util" }

external-request-validate = { path = "../../../external/ops/request-validate" }
game-version-get = { path = "../version-get" }
game-version-list = { path = "../version-list" }
mm-config-game-get = { path = "../../../mm-config/ops/game-get" }
region-get = { path = "../../../region/ops/get" }
tier-list = { path = "../../../tier/ops/list" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
faker-game = { path = "../../../faker/ops/game" }
