[package]
name = "chirp-worker"
description = "Server manager for running a Chirp worker."
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = ["attributes"]
attributes = ["chirp-worker-attributes", "tracing-subscriber"]

[dependencies]
async-trait = "0.1"
chirp-client = { path = "../client" }
global-error = { path = "../../global-error", features = ["chirp"] }
chirp-metrics = { path = "../metrics" }
chirp-perf = { path = "../perf" }
chirp-worker-attributes = { path = "../worker-attributes", optional = true }
futures-util = "0.3"
formatted-error = { path = "../../formatted-error" }
indoc = "1.0"
lazy_static = "1.4"
prost = "0.10"
rand = "0.8"
rivet-cache = { path = "../../cache/build" }
rivet-connection = { path = "../../connection" }
rivet-metrics = { path = "../../metrics" }
rivet-operation = { path = "../../operation/core" }
rivet-pools = { path = "../../pools" }
rivet-runtime = { path = "../../runtime" }
rivet-util = { path = "../../util/core" }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40", features = ["full", "tracing"] }
tracing = "0.1"
types-proto = { path = "../../types-proto/core" }
tracing-subscriber = { version = "0.3", optional = true, default-features = false, features = [
	"fmt",
	"json",
	"ansi",
] } # Used with attribute
rivet-config = { path = "../../config" }
rivet-env = { path = "../../env" }
url = "2.4"

[dependencies.uuid]
version = "1.1"
features = ["v4", "serde"]

[dependencies.redis]
# TODO: https://github.com/rivet-gg/rivet/issues/508
path = "../../../../externals/redis-rs/redis"
default-features = false
features = [
	"keep-alive",
	"aio",
	"tokio-comp",
	"tokio-native-tls-comp",
	"connection-manager",
	"script",
	"streams",
]

[dev-dependencies]
testcontainers = "0.12"
rivet-test-images = { path = "../../test-images" }
