[service]
name = "api-identity"

[runtime]
kind = "rust"

[api]

[[api.router.mounts]]
path = "/identity"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "identity.api"

[databases]
db-team-dev = {}
