[package]
name = "user-pending-delete-toggle"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-operation = { path = "../../../../common/operation/core" }
chirp-client = { path = "../../../../common/chirp/client" }
prost = "0.10"

user-identity-get = { path = "../../../user-identity/ops/get" }

[dependencies.sqlx]
path = "../../../../../externals/sqlx"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../common/chirp/worker" }

faker-user = { path = "../../../faker/ops/user" }
user-identity-create = { path = "../../../user-identity/ops/create" }
