[package]
name = "faker-game"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
prost = "0.10"

cloud-game-config-create = { path = "../../../cloud/ops/game-config-create" }
faker-game-namespace = { path = "../game-namespace" }
faker-game-version = { path = "../game-version" }
faker-team = { path = "../team" }
game-create = { path = "../../../game/ops/create" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

game-get = { path = "../../../game/ops/get" }
