[package]
name = "mm-config-version-prepare"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
heck = "0.3"
prost = "0.10"
reqwest = "0.11"
rivet-operation = { path = "../../../../../lib/operation/core" }
s3-util = { path = "../../../../../lib/s3-util" }
nomad-client = "0.0.9"

build-get = { path = "../../../build/ops/get" }
upload-get = { path = "../../../upload/ops/get" }
region-get = { path = "../../../region/ops/get" }
tier-list = { path = "../../../tier/ops/list" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
util-mm = { package = "rivet-util-mm", path = "../../../mm/util" }

faker-build = { path = "../../../faker/ops/build" }
faker-game = { path = "../../../faker/ops/game" }
faker-region = { path = "../../../faker/ops/region" }
