[package]
name = "gasoline"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
gasoline-macros.workspace = true
cjson.workspace = true
dirs.workspace = true
udb-util.workspace = true
universaldb.workspace = true
futures-util.workspace = true
hex.workspace = true
include_dir.workspace = true
itertools.workspace = true
lazy_static.workspace = true
lz4_flex.workspace = true
md5.workspace = true
opentelemetry.workspace = true
papaya.workspace = true
portpicker.workspace = true
rivet-cache.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true
rivet-metrics.workspace = true
rivet-pools.workspace = true
rivet-runtime.workspace = true
rivet-test-deps.workspace = true
rivet-util.workspace = true
serde_json.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-logfmt.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing.workspace = true
universalpubsub.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
rand.workspace = true
statrs.workspace = true
dirs.workspace = true
rivet-runtime.workspace = true
