[package]
name = "pegboard"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-workflow = { path = "../../../lib/chirp-workflow/core" }
serde = { version = "1.0.198", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
thiserror = "1.0"

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false
features = [ "json", "ipnetwork" ]
