[package]
name = "pegboard"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-workflow = { path = "../../../lib/chirp-workflow/core" }
tokio-tungstenite = "0.23.1"
serde = { version = "1.0.198", features = ["derive"] }
