[package]
name = "upload-complete"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client = { path = "../../../../common/chirp/client" }
rivet-operation = { path = "../../../../common/operation/core" }
chrono = "0.4"
prost = "0.10"
s3-util = { path = "../../../../common/s3-util" }
url = "2.2"

[dependencies.sqlx]
path = "../../../../../externals/sqlx"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../common/chirp/worker" }
reqwest = "0.11"

upload-get = { path = "../get" }
upload-prepare = { path = "../prepare" }
