[package]
name = "universaldb"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
deadpool-postgres.workspace = true
foundationdb-tuple.workspace = true
futures-util.workspace = true
lazy_static.workspace = true
rand.workspace = true
rivet-metrics.workspace = true
rocksdb.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-postgres.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
rivet-config.workspace = true
rivet-env.workspace = true
rivet-pools.workspace = true
rivet-test-deps-docker.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
