[package]
name = "cloud-default-create"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
chirp-workflow.workspace = true
reqwest = "0.11"
rivet-connection.workspace = true
rivet-pools.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"
tracing-logfmt = "0.3"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
uuid = { version = "1", features = ["v4"] }

cloud-game-config-create.workspace = true
cloud-namespace-create.workspace = true
cloud-version-publish.workspace = true
pegboard.workspace = true
game-create.workspace = true
game-namespace-create.workspace = true
game-namespace-resolve-name-id.workspace = true
game-resolve-name-id.workspace = true
rivet-config.workspace = true
rivet-operation.workspace = true
team-resolve-display-name.workspace = true
user.workspace = true

[dev-dependencies]
chirp-worker.workspace = true
