[package]
name = "monolith-workflow-worker"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-workflow = { path = "../../../../../lib/chirp-workflow/core" }
rivet-health-checks = { path = "../../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../../lib/metrics" }
rivet-runtime = { path = "../../../../../lib/runtime" }

cluster = { path = "../../../cluster" }
ds = { path = "../../../ds" }
job-run = { path = "../../../job-run" }
linode = { path = "../../../linode" }
pegboard = { path = "../../../pegboard" }
