[service]
name = "cluster-worker"

[runtime]
kind = "rust"

[consumer]

[secrets]
"rivet/api_traefik_provider/token" = {}
"cloudflare/terraform/auth_token" = { optional = true }
"ssh/server/private_key_openssh" = {}

[databases]
bucket-build = {}
