[package]
name = "api-matchmaker"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-convert.workspace = true
api-helper.workspace = true
async-trait = "0.1"
bytes = "1.0"
chirp-client.workspace = true
rivet-operation.workspace = true
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rivet-api.workspace = true
rivet-cache.workspace = true
rivet-claims.workspace = true
rivet-health-checks.workspace = true
rivet-matchmaker-server.workspace = true
rivet-pools.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"
util-mm.workspace = true
uuid = { version = "1", features = ["v4"] }

captcha-request.workspace = true
captcha-turnstile-config-get.workspace = true
captcha-verify.workspace = true
cdn-namespace-get.workspace = true
game-namespace-get.workspace = true
game-namespace-resolve-url.workspace = true
game-resolve-namespace-id.workspace = true
captcha-hcaptcha-config-get.workspace = true
job-run.workspace = true
mm-config-lobby-group-resolve-version.workspace = true
mm-config-version-get.workspace = true
mm-dev-player-token-create.workspace = true
mm-lobby-get.workspace = true
mm-lobby-list-for-namespace.workspace = true
mm-lobby-player-count.workspace = true
mm-lobby-state-get.workspace = true
region-get.workspace = true
region-recommend.workspace = true
region-resolve-for-game.workspace = true
token-create.workspace = true
token-revoke.workspace = true
user-identity-get.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true

[dev-dependencies]
reqwest = "0.11"
rivet-connection.workspace = true
util-job.workspace = true

cdn-namespace-domain-create.workspace = true
cloud-namespace-token-development-create.workspace = true
cloud-namespace-token-public-create.workspace = true
faker-build.workspace = true
faker-game.workspace = true
faker-game-namespace.workspace = true
faker-game-version.workspace = true
faker-region.workspace = true
game-get.workspace = true
