[package]
name = "chat-thread-participant-list"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core", features = [] }
chirp-client = { path = "../../../../../lib/chirp/client" }
prost = "0.10"

chat-thread-get = { path = "../get" }
team-member-list = { path = "../../../team/ops/member-list" }
party-member-list = { path = "../../../party/ops/member-list" }
user-get = { path = "../../../user/ops/get" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

chat-thread-get-or-create-for-topic = { path = "../get-or-create-for-topic" }
chat-thread-get-for-topic = { path = "../get-for-topic" }
faker-user = {path = "../../../faker/ops/user" }
