[package]
name = "email-verification-create"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client = { path = "../../../../common/chirp/client" }
rivet-operation = { path = "../../../../common/operation/core" }
chrono = "0.4"
email-address-parser = "1.0.1"
prost = "0.10"
rand = "0.8"
serde_json = "1.0"

email-send = { path = "../../../email/ops/send" }
game-get = { path = "../../../game/ops/get" }

[dependencies.sqlx]
path = "../../../../../externals/sqlx"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../common/chirp/worker" }
reqwest = "0.11"

faker-game = { path = "../../../faker/ops/game" }
game-logo-upload-complete = { path = "../../../game/ops/logo-upload-complete" }
upload-prepare = { path = "../../../upload/ops/prepare" }
