[package]
name = "rivet-health-checks"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client = { path = "../chirp/client" }
global-error = { path = "../global-error" }
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }
rivet-config = { path = "../config" }
rivet-pools = { path = "../pools" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.36", features = ["tracing"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
