[service]
name = "api-auth"
[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/auth"
subdomain = "api"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "auth.api"

[secrets]
"turnstile/rivet_gg/secret_key" = { optional = true }
