[package]
name = "pegboard-config"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
schemars = { version = "0.8.21", features = ["url", "uuid1"] }
serde = { version = "1.0.195", features = ["derive"] }
url = "2.2.2"
uuid = { version = "1.6.1", features = ["v4"] }
pegboard.workspace = true
