[package]
name = "nomad-util"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
base64 = "0.13"
bytes = "1.0"
futures-util = "0.3"
global-error = { path = "../global-error" }
nomad-client = "0.0.9"
reqwest = { version = "0.11", features = ["stream"] }
rivet-config = { path = "../config" }
rivet-pools = { path = "../pools" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
thiserror = "1.0"
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"

[dependencies.nomad_client_new]
package = "nomad_client"
path = "../../../externals/nomad-client"
