[package]
name = "cdn-version-publish"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-operation = { path = "../../../../common/operation/core" }
chirp-client = { path = "../../../../common/chirp/client" }
prost = "0.10"
unzip-n = "0.1.2"
itertools = "0.10.5"

[dependencies.sqlx]
path = "../../../../../externals/sqlx"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../common/chirp/worker" }

cdn-version-get = { path = "../version-get" }
faker-game = { path = "../../../faker/ops/game" }
faker-cdn-site = { path = "../../../faker/ops/cdn-site" }
