[package]
name = "load-test-watch-requests"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
chirp-workflow.workspace = true
rivet-operation.workspace = true
rivet-connection.workspace = true
rivet-runtime.workspace = true
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
tracing-logfmt = "0.3"
rivet-api.workspace = true
reqwest = "0.11"

faker-game.workspace = true
faker-team.workspace = true
user.workspace = true
token-create.workspace = true
rivet-config.workspace = true

[dev-dependencies]
chirp-worker.workspace = true
