[package]
name = "api-games"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
api-helper.workspace = true
chirp-client.workspace = true
chirp-workflow.workspace = true
rivet-operation.workspace = true
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
rivet-api.workspace = true
rivet-cache.workspace = true
rivet-claims.workspace = true
rivet-health-checks.workspace = true
rivet-convert.workspace = true
rivet-pools.workspace = true
s3-util.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
tokio = { version = "1.40" }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
url = "2.2.2"
util-team.workspace = true
uuid = { version = "1", features = ["v4"] }

build-create.workspace = true
build-get.workspace = true
build-list-for-env.workspace = true
cluster.workspace = true
build.workspace = true
ds.workspace = true
game-get.workspace = true
game-namespace-get.workspace = true
game-version-get.workspace = true
team-get.workspace = true
token-revoke.workspace = true
token-create.workspace = true
upload-complete.workspace = true
upload-get.workspace = true
user.workspace = true
user-identity-get.workspace = true
rivet-config.workspace = true
rivet-env.workspace = true

[dev-dependencies]
rivet-connection.workspace = true
reqwest = "0.11"

cdn-namespace-domain-create.workspace = true
cloud-namespace-token-development-create.workspace = true
cloud-namespace-token-public-create.workspace = true
faker-build.workspace = true
faker-game.workspace = true
faker-game-namespace.workspace = true
faker-game-version.workspace = true
faker-region.workspace = true
game-get.workspace = true
region-get.workspace = true
