[package]
name = "dynamic-config"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-workflow.workspace = true
indoc = "2.0.5"
rivet-config.workspace = true
rivet-operation.workspace = true
tokio.workspace = true
