[package]
name = "rivet-util-mm"
version = "0.1.0"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
bit-vec = "0.6"
chirp-client = { path = "../../../../lib/chirp/client" }
heck = "0.3"
http = "0.2"
rivet-operation = { path = "../../../../lib/operation/core" }
rivet-util = { path = "../../../../lib/util/core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = { version = "0.24", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }

ip-info = { path = "../../ip/ops/info" }
mm-lobby-list-for-user-id = { path = "../ops/lobby-list-for-user-id" }
region-get = { path = "../../region/ops/get" }
user-identity-get = { path = "../../user-identity/ops/get" }