[service]
name = "api-cf-verification"

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/cf-verification"
subdomain = "api"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "cf-verification.api"

