[package]
name = "rivet-service-manager"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.89"
global-error = { path = "../global-error" }
tokio = { version = "1.40", features = ["full", "tracing"] }
rivet-health-checks = { path = "../health-checks" }
rivet-metrics = { path = "../metrics" }
rivet-pools = { path = "../pools" }
tracing = "0.1.40"
include_dir = "0.7.4"
rivet-config = { path = "../config" }
tokio-cron-scheduler = "0.13.0"
chrono = "0.4.38"

