[package]
name = "ip-info"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
chrono = "0.4"
prost = "0.10"
reqwest = { version = "0.12", features = ["json"] }
rivet-operation.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.sqlx]
workspace = true

[dev-dependencies]
chirp-worker.workspace = true
