[package]
name = "load-test-mm"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chirp-client.workspace = true
rivet-claims.workspace = true
rivet-operation.workspace = true
rivet-connection.workspace = true
rivet-runtime.workspace = true
tokio.workspace = true
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
tracing-logfmt = "0.3"
rivet-api.workspace = true
reqwest = "0.11"

cloud-namespace-token-public-create.workspace = true
faker-build.workspace = true
faker-game.workspace = true
faker-game-namespace.workspace = true
faker-game-version.workspace = true
faker-region.workspace = true
mm-config-namespace-config-set = { path = '../../../mm-config/ops/namespace-config-set' }
mm-lobby-list-for-namespace = { path = '../../../mm/ops/lobby-list-for-namespace' }
mm-player-count-for-namespace = { path = '../../../mm/ops/player-count-for-namespace' }
mm-lobby-player-count = { path = '../../../mm/ops/lobby-player-count' }
region-get.workspace = true
token-create.workspace = true
rivet-config.workspace = true


[dev-dependencies]
chirp-worker.workspace = true
