[package]
name = "api-matchmaker"
version = "0.0.1"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
rivet-convert = { path = "../../../lib/convert" }
api-helper = { path = "../../../lib/api-helper/build" }
async-trait = "0.1"
bytes = "1.0"
chirp-client = { path = "../../../lib/chirp/client" }
rivet-operation = { path = "../../../lib/operation/core" }
chrono = "0.4"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "stream", "tcp"] }
lazy_static = "1.4"
prost = "0.10"
rivet-api = { path = "../../../sdks/full/rust" }
rivet-cache = { path = "../../../lib/cache/build" }
rivet-claims = { path = "../../../lib/claims" }
rivet-health-checks = { path = "../../../lib/health-checks" }
rivet-matchmaker-server = { path = "../../../lib/smithy-output/api-matchmaker/rust-server" }
rivet-pools = { path = "../../../lib/pools" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
url = "2.2.2"
util-mm = { package = "rivet-util-mm", path = "../../pkg/mm/util" }
uuid = { version = "1", features = ["v4"] }

captcha-request = { path = "../../pkg/captcha/ops/request" }
captcha-turnstile-config-get = { path = "../../pkg/captcha/ops/turnstile-config-get" }
captcha-verify = { path = "../../pkg/captcha/ops/verify" }
cdn-namespace-get = { path = "../../pkg/cdn/ops/namespace-get" }
game-namespace-get = { path = "../../pkg/game/ops/namespace-get" }
game-namespace-resolve-url = { path = "../../pkg/game/ops/namespace-resolve-url" }
game-resolve-namespace-id = { path = "../../pkg/game/ops/resolve-namespace-id" }
game-user-get = { path = "../../pkg/game-user/ops/get" }
captcha-hcaptcha-config-get = { path = "../../pkg/captcha/ops/hcaptcha-config-get" }
job-run = { path = "../../pkg/job-run" }
mm-config-lobby-group-resolve-version = { path = "../../pkg/mm-config/ops/lobby-group-resolve-version" }
mm-config-version-get = { path = "../../pkg/mm-config/ops/version-get" }
mm-dev-player-token-create = { path = "../../pkg/mm/ops/dev-player-token-create" }
mm-lobby-get = { path = "../../pkg/mm/ops/lobby-get" }
mm-lobby-list-for-namespace = { path = "../../pkg/mm/ops/lobby-list-for-namespace" }
mm-lobby-player-count = { path = "../../pkg/mm/ops/lobby-player-count" }
mm-lobby-state-get = { path = "../../pkg/mm/ops/lobby-state-get" }
region-get = { path = "../../pkg/region/ops/get" }
region-recommend = { path = "../../pkg/region/ops/recommend" }
region-resolve-for-game = { path = "../../pkg/region/ops/resolve-for-game" }
token-create = { path = "../../pkg/token/ops/create" }
token-revoke = { path = "../../pkg/token/ops/revoke" }
user-identity-get = { path = "../../pkg/user-identity/ops/get" }

[dev-dependencies]
reqwest = "0.11"
rivet-connection = { path = "../../../lib/connection" }
util-job = { package = "rivet-util-job", path = "../../pkg/job/util" }

cdn-namespace-domain-create = { path = "../../pkg/cdn/ops/namespace-domain-create" }
cloud-namespace-token-development-create = { path = "../../pkg/cloud/ops/namespace-token-development-create" }
cloud-namespace-token-public-create = { path = "../../pkg/cloud/ops/namespace-token-public-create" }
faker-build = { path = "../../pkg/faker/ops/build" }
faker-game = { path = "../../pkg/faker/ops/game" }
faker-game-namespace = { path = "../../pkg/faker/ops/game-namespace" }
faker-game-version = { path = "../../pkg/faker/ops/game-version" }
faker-region = { path = "../../pkg/faker/ops/region" }
game-get = { path = "../../pkg/game/ops/get" }
