[package]
name = "ds"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
bit-vec = "0.6"
chirp-client = { path = "../../common/chirp/client" }
chirp-worker = { path = "../../common/chirp/worker" }
chirp-workflow = { path = "../../common/chirp-workflow/core" }
chrono = "0.4"
cjson = "0.1"
heck = "0.3"
hex = "0.4"
http = "0.2"
lazy_static = "1.4.0"
nix = { version = "0.27", default-features = false, features = ["signal"] }
nomad-client-old = { package = "nomad-client", version = "0.0.9" }
nomad-util = { path = "../../common/nomad-util" }
rand = "0.8"
regex = "1.10"
reqwest = { version = "0.12", features = ["json"] }
rivet-api = { path = "../../../sdks/full/rust" }
rivet-convert = { path = "../../common/convert" }
rivet-health-checks = { path = "../../common/health-checks" }
rivet-metrics = { path = "../../common/metrics" }
rivet-operation = { path = "../../common/operation/core" }
rivet-runtime = { path = "../../common/runtime" }
rivet-util = { path = "../../common/util/core" }
s3-util = { path = "../../common/s3-util" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sha2 = "0.10"
strum = { version = "0.24", features = ["derive"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "json",
    "ansi",
] }
util-build = { package = "rivet-util-build", path = "../build/util" }
util-job = { package = "rivet-util-job", path = "../job/util" }
uuid = { version = "1", features = ["v4", "serde"] }

build = { path = "../build" }
build-get = { path = "../build/ops/get" }
cluster = { path = "../cluster" }
ip-info = { path = "../ip/ops/info" }
mm-config-version-get = { path = "../mm-config/ops/version-get" }
mm-lobby-get = { path = "../mm/ops/lobby-get" }
mm-lobby-list-for-user-id = { path = "../mm/ops/lobby-list-for-user-id" }
pegboard = { path = "../pegboard" }
region-get = { path = "../region/ops/get" }
tier = { path = "../tier" }
token-create = { path = "../token/ops/create" }
upload-get = { path = "../upload/ops/get" }
user-identity-get = { path = "../user-identity/ops/get" }
rivet-config.workspace = true

[dependencies.sqlx]
path = "../../../externals/sqlx"
default-features = false

[dependencies.nomad_client]
package = "nomad_client"
path = "../../../externals/nomad-client"

[dev-dependencies]
cluster = { path = "../cluster" }
faker-build = { path = "../faker/ops/build" }
faker-game = { path = "../faker/ops/game" }
faker-region = { path = "../faker/ops/region" }
faker-user = { path = "../faker/ops/user" }
game-get = { path = "../game/ops/get" }
