[package]
name = "faker-team"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-operation.workspace = true
chirp-client.workspace = true
prost = "0.10"
chirp-workflow.workspace = true

faker.workspace = true

[dev-dependencies]
chirp-worker.workspace = true

team-get.workspace = true
