[package]
name = "rivet-engine"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "rivet-engine"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
gas.workspace = true
chrono.workspace = true
clap.workspace = true
colored_json.workspace = true
udb-util.workspace = true
universaldb.workspace = true
futures-util.workspace = true
hex.workspace = true
include_dir.workspace = true
lz4_flex.workspace = true
pegboard-runner-ws.workspace = true
reqwest.workspace = true
rivet-api-public.workspace = true
rivet-api-peer.workspace = true
rivet-bootstrap.workspace = true
rivet-cache.workspace = true
rivet-config.workspace = true
rivet-logs.workspace = true
rivet-pools.workspace = true
rivet-runtime.workspace = true
rivet-service-manager.workspace = true
rivet-term.workspace = true
rivet-util.workspace = true
rivet-workflow-worker.workspace = true
rivet-guard.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
strum.workspace = true
tabled.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
axum.workspace = true
base64.workspace = true
chrono.workspace = true
epoxy.workspace = true
futures-util.workspace = true
namespace.workspace = true
pegboard.workspace = true
portpicker.workspace = true
rand.workspace = true
rivet-api-public.workspace = true
rivet-runner-protocol.workspace = true
rivet-test-deps.workspace = true
rivet-util.workspace = true
rstest.workspace = true
tokio-tungstenite.workspace = true
tracing-subscriber.workspace = true
versioned-data-util.workspace = true
