[package]
name = "token-create"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
base64 = "0.13"
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
chrono = "0.4"
prost = "0.10"
rivet-claims = { path = "../../../../../lib/claims" }
jsonwebtoken = "8.2.0"
lazy_static = "1.4"

[dependencies.sqlx]
version = "0.6"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
