[service]
name = "api-route"
essential = true
priority = 70

[runtime]
kind = "rust"

[api]

[secrets]
"rivet/api_route/token" = {}

[databases]
redis-job = {}
redis-cdn = {}

[resources.single-node]
cpu = 50
memory = 64

[resources.distributed]
cpu = 250
memory = 256

