[package]
name = "game-namespace-version-set"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-operation = { path = "../../../../common/operation/core" }
chirp-client = { path = "../../../../common/chirp/client" }
prost = "0.10"

game-resolve-namespace-id = { path = "../resolve-namespace-id" }
game-get = { path = "../get" }
region-list-for-game = { path = "../../../region/ops/list-for-game" }
mm-lobby-idle-update = { path = "../../../mm/ops/lobby-idle-update" }

[dependencies.sqlx]
path = "../../../../../externals/sqlx"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../common/chirp/worker" }

faker-game = { path = "../../../faker/ops/game" }
game-version-create = { path = "../version-create" }
