[package]
name = "game-create"
version = "0.0.1"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
chirp-workflow = { path = "../../../../../lib/chirp-workflow/core" }
prost = "0.10"
rivet-operation = { path = "../../../../../lib/operation/core" }
util-team = { package = "rivet-util-team", path = "../../../team/util" }

cluster = { path = "../../../cluster" }
game-validate = { path = "../validate" }
team-get = { path = "../../../team/ops/get" }

[dependencies.sqlx]
git = "https://github.com/rivet-gg/sqlx"
rev = "08d6e61aa0572e7ec557abbedb72cebb96e1ac5b"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

faker-team = { path = "../../../faker/ops/team" }
