[package]
name = "rivet-server"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "rivet-server"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4.38"
clap = { version = "4.3", features = ["derive"] }
colored_json = "5.0.0"
global-error.workspace = true
include_dir = "0.7.4"
indoc = "2.0.5"
reqwest = "0.12.9"
rivet-api.workspace = true
rivet-migrate.workspace = true
rivet-pools.workspace = true
rivet-runtime.workspace = true
rivet-service-manager.workspace = true
rivet-term.workspace = true
s3-util.workspace = true
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml = "0.9.34"
strum = "0.26.3"
tabled = "0.17.0"
tempfile = "3.13.0"
thiserror = "1.0.64"
tokio = { version = "1.40", features = ["full", "tracing"] }
tracing = "0.1"
url = "2.4"
uuid = "1.10.0"

# Standalone
cluster-datacenter-tls-renew.workspace = true
cluster-gc.workspace = true
cluster-metrics-publish.workspace = true
job-gc.workspace = true
linode-gc.workspace = true
load-test-api-cloud.workspace = true
load-test-mm-sustain.workspace = true
load-test-mm.workspace = true
load-test-sqlx.workspace = true
load-test-watch-requests.workspace = true
mm-gc.workspace = true
monolith-worker.workspace = true
monolith-workflow-worker.workspace = true
nomad-monitor.workspace = true
pegboard-gc.workspace = true
pegboard-metrics-publish.workspace = true
pegboard-ws.workspace = true
workflow-gc.workspace = true
workflow-metrics-publish.workspace = true

# Cron
telemetry-beacon.workspace = true
user-delete-pending.workspace = true

# API
api-monolith-edge.workspace = true
api-monolith-public.workspace = true

# Oneshot
build-default-create.workspace = true
chirp-client.workspace = true
chirp-workflow.workspace = true
cloud-default-create.workspace = true
cluster-default-update.workspace = true
pegboard-dc-init.workspace = true
rivet-cache.workspace = true
rivet-config.workspace = true
rivet-connection.workspace = true
user-workflow-create.workspace = true

[dependencies.sqlx]
workspace = true
features = ["runtime-tokio", "postgres"]

