[service]
name = "api-status"

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/status"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "status.api"

[secrets]
"rivet/api_status/token" = {}
