[package]
name = "rivet-util-captcha"
version = "0.1.0"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
global-error = { path = "../../../../lib/global-error" }
serde_json = "1.0"
