[package]
name = "mm-config-lobby-group-resolve-name-id"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rivet-operation = { path = "../../../../common/operation/core" }
chirp-client = { path = "../../../../common/chirp/client" }
prost = "0.10"
util-mm = { package = "rivet-util-mm", path = "../../../mm/util" }

[dependencies.sqlx]
path = "../../../../../externals/sqlx"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../common/chirp/worker" }

faker-build = { path = "../../../faker/ops/build" }
faker-game = { path = "../../../faker/ops/game" }
faker-region = { path = "../../../faker/ops/region" }
faker-game-version = { path = "../../../faker/ops/game-version" }
