[package]
name = "user-presence-get"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
chrono = "0.4"
prost = "0.10"
util-user-presence = { package = "rivet-util-user-presence", path = "../../util" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
