name: bolt-check

on:
  - push
  - pull_request

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # Enable fail-fast behavior
    shell: bash -e {0}

env:
  store: /home/runner/nix

jobs:
  check:
    runs-on: [self-hosted, linux, x64]

    steps:
      # MARK: Git
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          submodules: recursive

      # sccache is used for caching Rust builds instead of GitHub Actions cache,
      # since the cache sizes needed are greater than 10GB, which isn't
      # supported by GitHub Actions.
      - uses: ./.github/actions/pre-init
        with:
          sccache_aws_secret_access_key: ${{ secrets.SCCACHE_AWS_SECRET_ACCESS_KEY }}
          sccache_aws_access_key_id: ${{ secrets.SCCACHE_AWS_ACCESS_KEY_ID }}

      - name: Bolt Generate Project
        run: nix-shell --pure --run "bolt gen project"

      - name: Bolt Check
        run: nix-shell --pure --run "bolt check -g --validate-format"

      - name: Force Parallel Failure
        if: failure()
        uses: andymckay/cancel-action@0.3
