name: detect-secrets

on: push

jobs:
  detect-secrets-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install detect-secrets
        run: pip install detect-secrets[gibberish]

      - name: Check for new secrets
        run: |
          ./scripts/detect_secrets/check.sh
