name: Continuous Release

on:
  pull_request:
    paths:
      - frontend/packages/cli/**
      - frontend/packages/create-actor/**
      - sdks/actor/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: corepack enable
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install
        
      - run: yarn build --filter='./{sdks,frontend/packages/cli,frontend/packages/create-actor}/**'
      # TODO: Add --compact once we publish cli to npm
      - run: rm -rf ./sdks/actor/client/node_modules; rm -rf ./frontend/packages/cli/node_modules; rm -rf ./frontend/packages/create-actor/node_modules
      - run: yarn dlx pkg-pr-new publish --yarn './sdks/actor/client' './frontend/packages/cli' './frontend/packages/create-actor'